server:
  port: 8081

jwt:
  issuer: jara
  subject: auth
  expire-time: 3600 # 1시간
  secret: my-secret

#spring:
#  r2dbc:
#    url: r2dbc:mariadb://localhost:3306/kotlin_jpa
#    username: kotlin_jpa
#    password: kotlin_jpa!@34

