server:
  port: 8080

spring:
  application:
    name: issue-api

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kotlin_jpa
    username: kotlin_jpa
    password: kotlin_jpa!@34

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

auth:
  url: http://localhost:8081/api/v1/users/me

logging:
  level:
    com:
      soon83: debug
